### PR TITLE
Make tessel API compatible with T2

### PR DESCRIPTION
**Pull request by johnnyman727**
This PR basically makes the T1 API compatible with T2. The only breaking change is changing the the `pin.read` callback return args from `(value)` to `(err, value)`. It also adds the option to provide callbacks to a bunch of pin functions to make it compatible with T2 (but those are backwards compatible).

### CODE REVIEW

**Comment by HipsterBrown** [comment]
Any way we can get some tests around this?

**Comment by johnnyman727** [comment]
@HipsterBrown we had a whole test suite for Tessel 1 so that anytime a change was introduced, it was run on the actual hardware. I'm trying to dig that up now.

**Comment by johnnyman727** [comment]
Also, it's a good thing I got that working because I initially broke `.read` :scream:

**Comment by johnnyman727** [comment]
Figured it out! Just had to connect G1 to G2, G3 to G5, SPI MOSI to SPI MISO on the GPIO port then run `npm test`. Output below, all tests passing (including new ones):
```
➜  t1-firmware git:(jon-t2-compat) ✗ npm test

> tessel-firmware@0.1.26 test /Users/Jon/Work/technical/t1-firmware
> cd test; npm install; npm test

npm WARN package.json tinytap@0.2.0 No repository field.

> test@0.0.0 test /Users/Jon/Work/technical/t1-firmware/test
> tinytap -e 'tessel run' *.js

1..12
 | TESSEL! Connected to TM-00-04-f000da30-0046473d-10b02586.
 | INFO Bundling directory /Users/Jon/Work/technical/t1-firmware/test
 | INFO Deploying bundle (1.22 MB)...
 | INFO Running script...
 | 1..1
 | 0
 | 1
 | 2
 | 3
 | 0
 | 1
 | 2
 | 3
 | 0
 | 1
 | 2
 | 3
 | 0
 | 1
 | 2
 | 3
 | ok
ok 1 - _simple.js
ok 2 - test exited with code 0
 | TESSEL! Connected to TM-00-04-f000da30-0046473d-10b02586.
 | INFO Bundling directory /Users/Jon/Work/technical/t1-firmware/test
 | INFO Deploying bundle (1.22 MB)...
 | INFO Running script...
 | 1..1
 | # Thu Feb 18 2016 03:47:45 GMT+0000 (GMT)
 | ok
ok 3 - date.js
ok 4 - test exited with code 0
 | TESSEL! Connected to TM-00-04-f000da30-0046473d-10b02586.
 | INFO Bundling directory /Users/Jon/Work/technical/t1-firmware/test
 | INFO Deploying bundle (1.22 MB)...
 | INFO Running script...
 | TAP version 13
 | # port name
 | # registering level listeners
 | ok 1 should not throw
 | ok 2 should not throw
 | # registering edge listeners
 | ok 3 should not throw
 | ok 4 should not throw
 | # Using "on" with level triggers
 | ok 5 Throws an error when using on with 'high'
 | # Using "on" with high level emits an error
 | ok 6 Emits an error when using on with 'high'
 | # Using "on" with low level triggers with an error
 | ok 7 Emits an error when using on with 'low'
 | # Does not throw an error with non-interrupt events
 | ok 8 Allows non-interrupt events to be used.'
 | # pin creates and clears interrupt datastructure
 | ok 9 pin has interrupts
 | ok 10 pin has edge interrupt
 | ok 11 pin has correct mode
 | ok 12 (unnamed assert)
 | # pin creates different types of interrupts
 | ok 13 pin has interrupts
 | ok 14 there are two different interrupts for this pin
 | ok 15 pin has edge interrupt
 | ok 16 pin has level interrupt
 | ok 17 pin has correct mode
 | ok 18 there are no more edge interrupts
 | ok 19 there are no more level interrupts
 | # real simple rise test
 | hit~ 535371810 rise
 | # real simple fall test
 | fall hit~ 535483103 fall
 | # real simple low test
 | low hit~ 535590867 low
 | # real simple high test
 | high hit~ 535701563 high
 | # remove all listeners with no specified mode
 | # removing change and have rise still work
 | ok 20 Both change and rise interrupts are set.
 | got the change...
 | got the time 536059021
 | ok 21 Both change and rise interrupts are set.
 | ok 22 There are no more listeners
 | # removing change and have rise and fall still work
 | ok 23 Both change and rise interrupts are set.
 | ok 24 All interrupts are set.
 | Fallign man!
 | ok 25 Both fall and rise interrupts are set.
 | # live event triggers with both modes
 | ok 26 there are two separate interrupts
 | # a bunch of repeated rises
 | rose  1  times
 | rose  2  times
 | rose  3  times
 | rose  4  times
 | rose  5  times
 | rose  6  times
 | # a bunch of repeated falls
 | fell  1  times
 | fell  2  times
 | fell  3  times
 | fell  4  times
 | fell  5  times
 | fell  6  times
 | # a bunch of repeated levels
 | # using too many interrupts, if you can believe it
 | ok 27 An error was thrown after using too many interrupts
 | # Removing one interrupt of two from the same pin
 | # Pull resistors
 | ok 28 should be equal
 | ok 29 should be equal
 | ok 30 should be equal
 | ok 31 should be equal
 | ok 32 should be equal
 | ok 33 should be equal
 | # async read write
 | setting output to true
 | inside output
 | ok 34 should be equal
 | ok 35 should be equal
 | ok 36 should be equal
 | ok 37 should be equal
 | ok 38 should be equal
 | ok 39 should be equal
 | # async high low toggle
 | ok 40 should be equal
 | ok 41 should be equal
 | ok 42 should be equal
 | ok 43 should be equal
 | ok 44 should be equal
 | ok 45 should be equal
 | ok 46 should be equal
 | ok 47 should be equal
 | ok 48 should be equal
 | # async pull mode
 | ok 49 should be equal
 | ok 50 should be equal
 | ok 51 should be equal
 | # async rawWrite rawRead
 | ok 52 should be equal
 | ok 53 should be equal
 | ok 54 should be equal
 |
 | 1..54
 | # tests 54
 | # pass  54
 |
 | # ok
 |
ok 5 - gpio.js
ok 6 - test exited with code 0
 | TESSEL! Connected to TM-00-04-f000da30-0046473d-10b02586.
 | INFO Bundling directory /Users/Jon/Work/technical/t1-firmware/test
 | INFO Deploying bundle (1.22 MB)...
 | INFO Running script...
 | TAP version 13
 | # small async transfer
 | ok 1 undefined
 | ok 2 should be equal
 | # batch transfer with chunks
 | ok 3 undefined
 | ok 4 should be equal
 | # batch transfer with chunks and repeating
 | ok 5 undefined
 | ok 6 should be equal
 | # batch transfer with no options
 | ok 7 undefined
 | ok 8 should be equal
 | # large async transfer
 | ok 9 undefined
 | ok 10 should be equal
 |
 | 1..10
 | # tests 10
 | # pass  10
 |
 | # ok
 |
ok 7 - spi.js
ok 8 - test exited with code 0
 | TESSEL! Connected to TM-00-04-f000da30-0046473d-10b02586.
 | INFO Bundling directory /Users/Jon/Work/technical/t1-firmware/test
 | INFO Deploying bundle (1.22 MB)...
 | INFO Running script...
 | TAP version 13
 | # testing input validation
 | ok 1 pulse type validation
 | ok 2 pulse timeout type validation
 | ok 3 pulse timeout bounds validation
 | # testing readPulse functionality
 | ok 4 error when animating neopixel
 | ok 5 neopixel tried using sct (in use by readPulse)
 | ok 6 no error when reading 250ms pulse
 | ok 7 high 250ms pulse
 | ok 8 no error when reading pulse
 | ok 9 low 350ms pulse
 | # pulse length 353.93285555556 with margin of error 0.25
 | ok 10 error when reading pulse
 | ok 11 high pulse timeout with sent pulse
 | ok 12 error when reading pulse
 | ok 13 readPulse tried using sct (in use by neopixels)
 | ok 14 no error when animating neopixels
 | ok 15 error when reading pulse
 | ok 16 readPulse tried using sct (in use by readPulse)
 | ok 17 error when reading pulse
 | ok 18 low pulse timeout without pulse sent
 |
 | 1..18
 | # tests 18
 | # pass  18
 |
 | # ok
 |
ok 9 - test_read_pulse.js
ok 10 - test exited with code 0
 | TESSEL! Connected to TM-00-04-f000da30-0046473d-10b02586.
 | INFO Bundling directory /Users/Jon/Work/technical/t1-firmware/test
 | INFO Deploying bundle (1.22 MB)...
 | INFO Running script...
 | 1..5
 | # can set dataBits
 | ok 1 equal
 | # can set parity
 | ok 2 equal
 | # bad dataBits setting throws an error
 | ok 3 ok
 | # bad parity setting throws an error
 | ok 4 ok
 | # bad stopBits setting throws an error
 | ok 5 ok
 | # pass 5 5
 | # fail 0 5
```

**Comment by HipsterBrown** [comment]
Rad! :clap:

**Comment by johnnyman727** [comment]
Yeah, we should really get a hardware test integration rig going for T2 soon.

**Pull request merged**
